---
- name: Unleash setup
  hosts: all
  become: true
  become_user: deploy
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: Clone Remote Git Repository
      git:
        repo: git clone git@github.com:Unleash/unleash.git
        dest: /home/deploy/unleash